SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

DROP TABLE IF EXISTS public.bookings CASCADE;
DROP TABLE IF EXISTS public.confirmed_event CASCADE;
DROP TABLE IF EXISTS public.event_slots CASCADE;
DROP TABLE IF EXISTS public.events CASCADE;
DROP TABLE IF EXISTS public.host_availability CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.participant_availability CASCADE;
DROP TABLE IF EXISTS public.user_availability CASCADE;
DROP TABLE IF EXISTS public.user_date_override_availability CASCADE;
DROP TABLE IF EXISTS public.user_meeting_preferences CASCADE;
DROP TABLE IF EXISTS public.user_oauth_tokens CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

CREATE TABLE public.bookings (
                                 id bigint NOT NULL,
                                 created_at timestamp(6) without time zone,
                                 end_time timestamp(6) without time zone NOT NULL,
                                 invitee_email character varying(255) NOT NULL,
                                 invitee_name character varying(255) NOT NULL,
                                 start_time timestamp(6) without time zone NOT NULL,
                                 status character varying(255) NOT NULL,
                                 timezone character varying(255),
                                 host_id bigint NOT NULL,
                                 CONSTRAINT bookings_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'CONFIRMED'::character varying, 'CANCELLED'::character varying])::text[])))
);

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.confirmed_event (
                                        id bigint NOT NULL,
                                        additional_note character varying(255),
                                        confirmed_at timestamp(6) without time zone,
                                        event_id bigint,
                                        slot_id bigint
);

ALTER TABLE public.confirmed_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.confirmed_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.event_slots (
                                    id bigint NOT NULL,
                                    created_at timestamp(6) without time zone,
                                    end_time time(0) without time zone NOT NULL,
                                    slot_date date NOT NULL,
                                    start_time time(0) without time zone NOT NULL,
                                    event_id bigint NOT NULL
);

ALTER TABLE public.event_slots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.event_slots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.events (
                               id bigint NOT NULL,
                               created_at timestamp(6) without time zone,
                               earliest_time time(0) without time zone,
                               latest_time time(0) without time zone,
                               share_link character varying(255),
                               slot_duration integer NOT NULL,
                               timezone character varying(255),
                               title character varying(255) NOT NULL,
                               host_id bigint NOT NULL
);

ALTER TABLE public.events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.host_availability (
                                          id bigint NOT NULL,
                                          created_at timestamp(6) without time zone,
                                          event_slot_id bigint NOT NULL,
                                          host_id bigint NOT NULL
);

ALTER TABLE public.host_availability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.host_availability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notifications (
                                      id bigint NOT NULL,
                                      action_url character varying(255),
                                      created_at timestamp(6) without time zone NOT NULL,
                                      is_read boolean NOT NULL,
                                      message character varying(1000),
                                      read_at timestamp(6) without time zone,
                                      related_entity_id bigint,
                                      related_entity_type character varying(255),
                                      title character varying(255) NOT NULL,
                                      type character varying(255) NOT NULL,
                                      user_id bigint NOT NULL,
                                      CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['EVENT_CREATED'::character varying, 'EVENT_UPDATED'::character varying, 'EVENT_CANCELLED'::character varying, 'BOOKING_PENDING'::character varying, 'BOOKING_CONFIRMED'::character varying, 'BOOKING_CANCELLED'::character varying, 'REMINDER'::character varying, 'SYSTEM'::character varying, 'INFO'::character varying])::text[])))
);

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.participant_availability (
                                                 id bigint NOT NULL,
                                                 created_at timestamp(6) without time zone,
                                                 participant_name character varying(255),
                                                 event_slot_id bigint NOT NULL
);

ALTER TABLE public.participant_availability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.participant_availability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_availability (
                                          id bigint NOT NULL,
                                          day_of_week character varying(255) NOT NULL,
                                          end_time time(0) without time zone NOT NULL,
                                          start_time time(0) without time zone NOT NULL,
                                          user_id bigint NOT NULL,
                                          CONSTRAINT user_availability_day_of_week_check CHECK (((day_of_week)::text = ANY ((ARRAY['MONDAY'::character varying, 'TUESDAY'::character varying, 'WEDNESDAY'::character varying, 'THURSDAY'::character varying, 'FRIDAY'::character varying, 'SATURDAY'::character varying, 'SUNDAY'::character varying])::text[])))
);

ALTER TABLE public.user_availability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_availability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_date_override_availability (
                                                        id bigint NOT NULL,
                                                        date date NOT NULL,
                                                        end_time time(0) without time zone,
                                                        start_time time(0) without time zone,
                                                        unavailable boolean,
                                                        user_id bigint NOT NULL
);

ALTER TABLE public.user_date_override_availability ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_date_override_availability_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_meeting_preferences (
                                                 id bigint NOT NULL,
                                                 buffer_time_minutes integer,
                                                 future_days_allowed integer,
                                                 meeting_duration_minutes integer,
                                                 min_notice_hours integer,
                                                 timezone character varying(255),
                                                 user_id bigint NOT NULL
);

ALTER TABLE public.user_meeting_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_meeting_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_oauth_tokens (
                                          id bigint NOT NULL,
                                          access_token text NOT NULL,
                                          created_at timestamp(6) without time zone,
                                          refresh_token text,
                                          token_expiry timestamp(6) without time zone,
                                          user_id bigint NOT NULL
);

ALTER TABLE public.user_oauth_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_oauth_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              created_at timestamp(6) without time zone,
                              email character varying(255),
                              google_id character varying(255),
                              name character varying(255),
                              password character varying(255),
                              profile_pic character varying(255),
                              timezone character varying(255)
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.bookings ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.confirmed_event ADD CONSTRAINT confirmed_event_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.event_slots ADD CONSTRAINT event_slots_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.events ADD CONSTRAINT events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.host_availability ADD CONSTRAINT host_availability_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.notifications ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.participant_availability ADD CONSTRAINT participant_availability_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.events ADD CONSTRAINT uk1itxo82pvpclbgv5lhh3wvxit UNIQUE (share_link);
ALTER TABLE ONLY public.user_oauth_tokens ADD CONSTRAINT uk6t097r5dj02okx9ovauggkkk0 UNIQUE (user_id);
ALTER TABLE ONLY public.user_meeting_preferences ADD CONSTRAINT ukcpu0gkpwp32s47fpnep0fwqvm UNIQUE (user_id);
ALTER TABLE ONLY public.confirmed_event ADD CONSTRAINT ukfkp338lxlt00yo2j7sp4r9d1m UNIQUE (event_id);
ALTER TABLE ONLY public.users ADD CONSTRAINT ukovh8xmu9ac27t18m56gri58i1 UNIQUE (google_id);
ALTER TABLE ONLY public.user_availability ADD CONSTRAINT user_availability_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_date_override_availability ADD CONSTRAINT user_date_override_availability_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_meeting_preferences ADD CONSTRAINT user_meeting_preferences_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_oauth_tokens ADD CONSTRAINT user_oauth_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.users ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.host_availability ADD CONSTRAINT fk3gptk7se4hjw8jaurtufutep6 FOREIGN KEY (host_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.user_oauth_tokens ADD CONSTRAINT fk605s0wb33vgdg5pbqe7agb4bj FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.user_meeting_preferences ADD CONSTRAINT fk7fs0jte42elos92xlbr9nmm6q FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.confirmed_event ADD CONSTRAINT fk8eu8fx7p9sgl41tegpdavo7f3 FOREIGN KEY (event_id) REFERENCES public.events(id);
ALTER TABLE ONLY public.bookings ADD CONSTRAINT fk9u1gnk2ri211c8933qy9lvd1e FOREIGN KEY (host_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.notifications ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.event_slots ADD CONSTRAINT fkfalh692br6259bovqpqlu8npy FOREIGN KEY (event_id) REFERENCES public.events(id);
ALTER TABLE ONLY public.participant_availability ADD CONSTRAINT fkgva3fq4xi4ek7ggtibuah00hs FOREIGN KEY (event_slot_id) REFERENCES public.event_slots(id);
ALTER TABLE ONLY public.user_availability ADD CONSTRAINT fkh3g4yjvo392hpgfk55231cjfm FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.confirmed_event ADD CONSTRAINT fkmdsno8l5cybv8613yaapew9sf FOREIGN KEY (slot_id) REFERENCES public.event_slots(id);
ALTER TABLE ONLY public.events ADD CONSTRAINT fknsvyk08eqkdlxp4d2httg2u8v FOREIGN KEY (host_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.user_date_override_availability ADD CONSTRAINT fkonbevtx09atqo1afkg79xdeam FOREIGN KEY (user_id) REFERENCES public.users(id);
ALTER TABLE ONLY public.host_availability ADD CONSTRAINT fkrevcmu2vilykxewng4pnjs7t2 FOREIGN KEY (event_slot_id) REFERENCES public.event_slots(id);